### ISSUE TITLE
Unable to DeploySSC as an atomic transaction

### ISSUE THREAD

**Issue by pgege** [scale-it/algo-builder#369]
Hello, I have been trying to run tests on my smart contracts using algo-builder. I have looked through your examples and docs to figure out how to deploy a stateful smart contract (I need it to be deployed as an atomic transaction). I came up with the following code based on the documentation:

```
describe('Stateful Contract Deployment', function () {
  let master;

  let runtime;

  const approvalProgram = getProgram('winner_approval.teal');
  const clearStateProgram = getProgram('participant_clear_state.teal');

  this.beforeEach(async function () {
    master = new AccountStore(masterBalance);
    runtime = new Runtime([master]);
  });

  it('Should not fail if app is deployed as an atomic transaction', () => {
    const validTxFee = 1000;

    transactionGroup = [
      {
        type: types.TransactionType.DeploySSC,
        sender: master.account,
        approvalProgram: approvalProgram,
        clearProgram: clearStateProgram,
        globalBytes: 5,
        globalInts: 4,
        localBytes: 0,
        localInts: 0,
        appArgs: [
          "int:0",
          "int:25412621"
        ],
        payFlags: { totalFee: validTxFee }
      }
    ]

    runtime.executeTx(transactionGroup);
  });
});
```
I have removed some snippets of my tests to highlight the problematic transaction which is the DeploySSC transaction. When I try to execute my test, the code crashes and produces the following error:
```
Error: address seems to be malformed
      at Object.<anonymous> (/home/paul/Desktop/test-algob/node_modules/algosdk/src/encoding/address.js:13:33)
      at Module._compile (internal/modules/cjs/loader.js:1068:30)
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
      at Module.load (internal/modules/cjs/loader.js:933:32)
      at Function.Module._load (internal/modules/cjs/loader.js:774:14)
      at Module.require (internal/modules/cjs/loader.js:957:19)
      at require (internal/modules/cjs/helpers.js:88:18)
      at Object.<anonymous> (/home/paul/Desktop/test-algob/node_modules/algosdk/src/main.js:3:17)
      at Module._compile (internal/modules/cjs/loader.js:1068:30)
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
      at Module.load (internal/modules/cjs/loader.js:933:32)
      at Function.Module._load (internal/modules/cjs/loader.js:774:14)
      at Module.require (internal/modules/cjs/loader.js:957:19)
      at require (internal/modules/cjs/helpers.js:88:18)
      at Object.<anonymous> (/home/paul/Desktop/test-algob/node_modules/algosdk/index.js:1:18)
      at Module._compile (internal/modules/cjs/loader.js:1068:30)
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
      at Module.load (internal/modules/cjs/loader.js:933:32)
      at Function.Module._load (internal/modules/cjs/loader.js:774:14)
      at Module.require (internal/modules/cjs/loader.js:957:19)
      at require (internal/modules/cjs/helpers.js:88:18)
      at Object.<anonymous> (/home/paul/Desktop/test-algob/node_modules/@algo-builder/runtime/build/account.js:4:19)
      at Module._compile (internal/modules/cjs/loader.js:1068:30)
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
      at Module.load (internal/modules/cjs/loader.js:933:32)
      at Function.Module._load (internal/modules/cjs/loader.js:774:14)
      at Module.require (internal/modules/cjs/loader.js:957:19)
      at require (internal/modules/cjs/helpers.js:88:18)
      at Object.<anonymous> (/home/paul/Desktop/test-algob/node_modules/@algo-builder/runtime/build/index.js:23:19)
      at Module._compile (internal/modules/cjs/loader.js:1068:30)
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
      at Module.load (internal/modules/cjs/loader.js:933:32)
      at Function.Module._load (internal/modules/cjs/loader.js:774:14)
      at Module.require (internal/modules/cjs/loader.js:957:19)
      at require (internal/modules/cjs/helpers.js:88:18)
      at Object.<anonymous> (/home/paul/Desktop/test-algob/node_modules/@algo-builder/algob/build/index.js:23:19)
      at Module._compile (internal/modules/cjs/loader.js:1068:30)
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
      at Module.load (internal/modules/cjs/loader.js:933:32)
      at Function.Module._load (internal/modules/cjs/loader.js:774:14)
      at Module.require (internal/modules/cjs/loader.js:957:19)
      at require (internal/modules/cjs/helpers.js:88:18)
      at Object.<anonymous> (test/sample-test.js:1:24)
      at Module._compile (internal/modules/cjs/loader.js:1068:30)
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
      at Module.load (internal/modules/cjs/loader.js:933:32)
      at Function.Module._load (internal/modules/cjs/loader.js:774:14)
      at ModuleWrap.<anonymous> (internal/modules/esm/translators.js:199:29)
      at ModuleJob.run (internal/modules/esm/module_job.js:152:23)
      at async Loader.import (internal/modules/esm/loader.js:177:24)
```

I have searched for answers to see if it's something that I'm doing wrong but there are no resources that show deploying a stateful smart contract as an atomic transaction. However, I would expect what I've done to be correct based on the documentation but it produces errors.

**Comment by amityadav0** [comment]
Hi
this error is encountered probably because `sign` parameter is not passed.
`sign: types.SignType.SecretKey,`
In tx Group, you should add sign type.
```
transactionGroup = [
      {
        type: types.TransactionType.DeploySSC,
        sign: types.SignType.SecretKey,
        sender: master.account,
        approvalProgram: approvalProgram,
        clearProgram: clearStateProgram,
        globalBytes: 5,
        globalInts: 4,
        localBytes: 0,
        localInts: 0,
        appArgs: [
          "int:0",
          "int:25412621"
        ],
        payFlags: { totalFee: validTxFee }
      }
    ]
```

**Comment by pgege** [comment]
Solved the problem, thanks!
