### ISSUE TITLE
TypeError: deployer.getSSCfromCPKey is not a function

### ISSUE THREAD

**Issue by pgege** [scale-it/algo-builder#381]
I've attempted to execute an atomic transaction within a script but get the following error:
```
TypeError: deployer.getSSCfromCPKey is not a function
    at Object.registerCheckpoints (/home/paul/Desktop/algo_proj/algo-builder/packages/algob/src/lib/script-checkpoints.ts:235:32)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at executeTransaction (/home/paul/Desktop/algo_proj/algo-builder/packages/algob/src/lib/tx.ts:243:5)
    at Object.run [as default] (/home/paul/Desktop/algo_proj/project_files/scripts/0-sampleScript.js:51:16)
    at Object.runScript (/home/paul/.config/yarn/global/node_modules/@algo-builder/algob/src/internal/util/scripts-runner.ts:75:5)
    at runSortedScripts (/home/paul/.config/yarn/global/node_modules/@algo-builder/algob/src/builtin-tasks/run.ts:108:5)
    at Object.runMultipleScripts (/home/paul/.config/yarn/global/node_modules/@algo-builder/algob/src/builtin-tasks/run.ts:66:5)
    at executeDeployTask (/home/paul/.config/yarn/global/node_modules/@algo-builder/algob/src/builtin-tasks/deploy.ts:85:10)
    at Environment._runTaskDefinition (/home/paul/.config/yarn/global/node_modules/@algo-builder/algob/src/internal/core/runtime-environment.ts:173:14)
    at Environment.run (/home/paul/.config/yarn/global/node_modules/@algo-builder/algob/src/internal/core/runtime-environment.ts:99:12)
```
Here is the code I'm running (I have written tests to execute this same transaction using `runtime.execute()` and it works for the tests but not here):
```
const {
  executeTransaction, 
} = require('@algo-builder/algob');
const { types } = require('@algo-builder/runtime');

async function run (_, deployer) {
  const contractOwnerAccount = deployer.accountsByName.get('contract_owner_1');
  const developerAccount = deployer.accountsByName.get('developer_1');
  const escrowAccount = await deployer.loadLogic('escrow_contract.teal');
  // const donorAccount = deployer.accountsByName.get('john');

  approvalProgram = 'winner_approval.teal';
  clearProgram = 'participant_clear_state.teal';

  const submissionBegin = 0;
  const submissionEnd = 15797462;
  const globalBytes = 5;
  const globalInts = 4;
  const validTxFee = 1000;
  const CONTRACT_FUNDS = 202000;

  let response;


  const algoTxnParams = [{
    type: types.TransactionType.DeploySSC,
    sign: types.SignType.SecretKey,
    fromAccount: contractOwnerAccount,
    approvalProgram,
    clearProgram,
    localInts: 0,
    localBytes: 0,
    globalInts,
    globalBytes,
    appArgs: [
      `int:${submissionBegin}`,
      `int:${submissionEnd}`
    ],
    payFlags: { totalFee: validTxFee }
  },
  {
    type: types.TransactionType.TransferAlgo,
    sign: types.SignType.SecretKey,
    fromAccount: contractOwnerAccount,
    toAccountAddr: escrowAccount.address(),
    amountMicroAlgos: CONTRACT_FUNDS,
    payFlags: { totalFee: validTxFee }
  }]

  try {
    response = await executeTransaction(deployer, algoTxnParams)
  } catch (error){
    console.log(error);
  }
```

**Comment by amityadav0** [comment]
Hi
it seems like when script is loading it is using `/home/paul/.config/yarn/global/node_modules/@algo-builder/algob/src/internal/util/scripts-runner.ts:75:5`, and while running it is using different version `/home/paul/Desktop/algo_proj/algo-builder/packages/algob/src/lib/script-checkpoints.ts:235:32`, looking what maybe the root cause

**Comment by amityadav0** [comment]
This issue is related to yarn not linking properly, we will be releasing algob version soon, so this won't be a problem.
But for now you can fix this issue by following these steps:
-  In your `~/.config/yarn/global/node_modules/@algo-builder` directory run  `yarn link "@algo-builder/algob"`(this assumes you have already run yarn link in algob repo folder which is true in your case)
This should fix it, if you get permission denied while using algob
- Go to `~/.yarn/bin` run `chmod +x algob`

**Comment by pgege** [comment]
Following the steps provided fixed it, thanks.

**Comment by amityadav0** [comment]
I would suggest to remove global algob if you are using examples from repo and local repo code.
or better option would be to use the latest release, we will be releasing it today.
