### ISSUE TITLE
Error: RUNTIME_ERR1028: Error encountered while parsing teal file: unknown opcode "txnas" for teal version #5

### ISSUE THREAD

**Issue by Lumene98** [scale-it/algo-builder#526]
## Describe the bug
A small note: I am using `develop` which I shouldn't.

I get this error while trying to use `Txn.application_args` inside of a `For` 

#### Expected Behavior
It should support txnas

#### Current Behavior
It throws, saying the opcode does not exist

Full StackTrace:

```
at opcodeFromSentence (algo-builder/packages/runtime/build/parser/parser.js:326:15)
      at parser (algo-builder/packages/runtime/build/parser/parser.js:414:29)
      at Interpreter.executeWithResult (algo-builder/packages/runtime/build/interpreter/interpreter.js:384:49)
      at Interpreter.execute (algo-builder/packages/runtime/build/interpreter/interpreter.js:365:29)
      at Runtime.run (algo-builder/packages/runtime/build/runtime.js:553:21)
      at Ctx.addApp (algo-builder/packages/runtime/build/ctx.js:206:22)
      at Runtime.addApp (algo-builder/packages/runtime/build/runtime.js:381:18)
```

## Steps to Reproduce

1.  Create a subroutine with a for and iterate through the AppArgs array

### Environment

- OS: [e.g. iOS] Ubuntu
- Node.js version: 16
- algob version: last(develop)

**Comment by ratik21** [comment]
Hi @Lumene98, `txnas` & related ops will be available after [this](https://github.com/scale-it/algo-builder/pull/520) is merged to develop. The PR is currently open. Sorry for trouble

**Comment by Lumene98** [comment]
> Hi @Lumene98, `txnas` & related ops will be available after [this](https://github.com/scale-it/algo-builder/pull/520) is merged to develop. The PR is currently open. Sorry for trouble

It's my bad, I wasn't aware of that
